name: "desafio_final_LH_Marcilio"
version: "1.0.0"
config-version: 2

profile: "default"
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "dbt_packages"

models:
  desafio_final_LH_Marcilio:
    intermediate:
      +materialized: view
    marts:
      +materialized: table
    staging:
      +materialized: view

seeds:
  desafio_final_LH_Marcilio:
    sap_adventure_works:
      schema: sap_adw
